name: CI/CD workflow

env:
  SERVER_IP: "51.91.125.163"
  SERVER_USER: root

on:
  push:
    branches: main

jobs:
  check-tests-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server
    steps:
      - name: checkout le code
        uses: actions/checkout@v4
      - name: installer node.js
        uses: actions/setup-node@v7
        with:
          cache: "npm"
          cache-dependency-path: ./server/package-lock.json
      - name: install dependencies
        run: npm ci --prefer-offline 
      - name: vérifie le code
        run: npm run lint
      - name: vérifie les vulnérabilités des dépendances
        run: npm audit --audit-level=critical
      - name: éxécute les tests
        run: npm run test:ci

  check-frontend:
      runs-on: ubuntu-latest
      defaults:
        run:
          working-directory: ./client
      steps:
        - name: checkout le code
          uses: actions/checkout@v4
        - name: installer node.js
          uses: actions/setup-node@v4
          with:
            cache: "npm"
            cache-dependency-path: ./client/package-lock.json
        - name: install dependencies
          run: npm ci --prefer-offline --legacy-peer-deps
        - name: vérifie le code
          run: npm run lint
        - name: vérifie les vulnérabilités des dépendances
          run: npm audit --audit-level=critical

  build-frontend:
    needs: check-frontend
    runs-on: ubuntu-latest
    defaults:
        run:
          working-directory: ./client
    steps:
        - name: checkout le code
          uses: actions/checkout@v4
        - name: installer node.js
          uses: actions/setup-node@v4
          with:
            cache: "npm"
            cache-dependency-path: ./client/package-lock.json
        - name: install dependencies
          run: npm ci --prefer-offline --legacy-peer-deps
        - name: build application frontend
          run: npm run build
        - name: upload build artifact
          uses: actions/upload-artifact@v6
          with:
            name: build
            path: ./client/dist

  test-e2e-frontend:
    needs: build-frontend
    runs-on: ubuntu-latest
    steps:
        - name: checkout le code
          uses: actions/checkout@v4
        - name: installer node.js
          uses: actions/setup-node@v4
          with:
            cache: "npm"
            cache-dependency-path: '**/package-lock.json'
        - name: install dependencies
          run: | 
            cd server  
            npm ci --prefer-offline --legacy-peer-deps
        - name: download build artifact
          uses: actions/upload-artifact@v6
          with:
            name: build
            path: ./client/dist
        - name: start backend
          run: |
            cd server
            npm start & 
        - name: exec cypress
          uses: cypress-io/github-action@v6
          with: 
            working-directory: ./client
            browser: chrome
            start: npm run preview
            wait-on: http://localhost:4173
            wait-on-timeout: 60
            config: baseUrl=http://localhost:4173 

 
   
          


  deploy:
    needs: [check-tests-backend,test-e2e-frontend]
    runs-on: ubuntu-latest
    steps:
      - name: checkout le code 
        uses: actions/checkout@v4
      - name: download build artifact
        uses: actions/download-artifact@v6
        with:
          name: build
          path: ./dist
      - name: déployer le serveur 
        run: |
          set -x
          eval $(ssh-agent -s)
          ssh-add - <<< "${{ secrets.SSH_KEY_VPS }}"
          mkdir -p ~/.ssh
          ssh-keyscan -H $SERVER_IP >> ~/.ssh/known_hosts
          scp -r ./server $SERVER_USER@$SERVER_IP:/var/www
          scp -r ./dist $SERVER_USER@$SERVER_IP:/var/www/dist
          ssh $SERVER_USER@$SERVER_IP "export PATH=\$PATH:/home/ubuntu/.nvm/versions/node/v24.20.0/bin && cd /var/www && npm install --omit=dev"
          ssh $SERVER_USER@$SERVER_IP "export PATH=\$PATH:/home/ubuntu/.nvm/versions/node/v24.20.0/bin && cd /var/www && pm2 startOrRestart ecosystem.config.js --env production && pm2 save"